//
//  SelectorDetailInteractor.swift
//  ViperTech
//
//  Created by Adria Ros Saez on 10/19/18.
//  Copyright (c) 2018 adriaros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SelectorDetailInteractor: SelectorDetailPresenterToInteractorProtocol{
    
    var presenter: SelectorDetailInteractorToPresenterProtocol?
 
}
