//
//  SelectorInteractor.swift
//  ViperTech
//
//  Created by Adria Ros Saez on 10/18/18.
//  Copyright (c) 2018 adriaros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SelectorInteractor: SelectorPresenterToInteractorProtocol{
    
    var presenter: SelectorInteractorToPresenterProtocol?
    
    func fetchSomething() {
    }
}
