//
//  SelectorInteractor.swift
//  ViperTech
//
//  Created by Adria Ros Saez on 10/18/18.
//  Copyright (c) 2018 adriaros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SelectorInteractor: SelectorPresenterToInteractorProtocol{
    
    var presenter: SelectorInteractorToPresenterProtocol?
    
    func fetchList() {
        
        APIClient.getDefaultList() { (DTO, error) in
            
            if error != nil {
                guard let error = error else { return }
                self.presenter?.fetchedListDataFailed(error)
            } else {
                guard let results = DTO?.results else { return }
                self.presenter?.fetchedListDataSuccess(results)
            }
            
        }
    }
    
    func search(withInfo: String) {
        let item = translateSearch(item: withInfo)
        Constants.Networking.Url.item_search = item
        getSpecificList()
    }
    
    private func translateSearch(item: String) -> String {
        if item.contains(" "){
            return item.replacingOccurrences(of: " ", with: "+")
        } else {
            return item
        }
    }
    
    private func getSpecificList(){
        APIClient.getSearchList() { (DTO, error) in
            
            if error != nil {
                guard let error = error else { return }
                self.presenter?.fetchedListDataFailed(error)
            } else {
                guard let results = DTO?.results else { return }
                self.presenter?.fetchedListDataSuccess(results)
            }
            
        }
    }
}
